(function (root) {
  'use strict';

  // ---- seeded RNG (mulberry32, seeded from an FNV-1a hash of a string) ----
  // Same date string always produces the same puzzle for every player, with
  // no server involved (Wordle-style daily numbering).

  function seedFromString(str) {
    var h = 2166136261 >>> 0;
    for (var i = 0; i < str.length; i++) {
      h ^= str.charCodeAt(i);
      h = Math.imul(h, 16777619);
    }
    return h >>> 0;
  }

  function mulberry32(seed) {
    var state = seed >>> 0;
    return function () {
      state = (state + 0x6D2B79F5) | 0;
      var t = Math.imul(state ^ (state >>> 15), 1 | state);
      t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
  }

  function shuffleInPlace(arr, rand) {
    for (var i = arr.length - 1; i > 0; i--) {
      var j = Math.floor(rand() * (i + 1));
      var tmp = arr[i]; arr[i] = arr[j]; arr[j] = tmp;
    }
    return arr;
  }

  // ---- Hamiltonian path search ----
  //
  // The puzzle is generated by drawing the solution line FIRST (a path that
  // visits every cell exactly once), then stamping numbers onto cells along
  // that line. Because the numbers are just labels on an already-complete
  // route, the puzzle is guaranteed solvable by construction — there's no
  // separate "does this puzzle have an answer" check to get wrong.
  //
  // A grid's cells are bipartite by (row+col) parity (checkerboard colors).
  // A path alternates colors every step, so a path covering an ODD number of
  // cells (5x5 = 25) must start and end on the majority color: with 13
  // majority-color cells and 12 minority, positions 0,2,4,...,24 (13 of them)
  // land on whichever color the path starts on, so starting on the minority
  // color makes full coverage impossible outright, not just hard to find.
  // For even grids (6x6 = 36) both colors have equal counts, so any start
  // works. We only ever pick a start cell that this parity check allows.

  function findHamiltonianPath(n, rand) {
    var size = n * n;
    var idx = function (r, c) { return r * n + c; };
    var visited = new Uint8Array(size);
    var path = new Int32Array(size);
    var depth = 0;

    function neighbors(cellIdx) {
      var r = Math.floor(cellIdx / n), c = cellIdx % n;
      var out = [];
      if (r > 0) out.push(idx(r - 1, c));
      if (r < n - 1) out.push(idx(r + 1, c));
      if (c > 0) out.push(idx(r, c - 1));
      if (c < n - 1) out.push(idx(r, c + 1));
      return out;
    }

    function unvisitedDegree(cellIdx) {
      var nbs = neighbors(cellIdx), count = 0;
      for (var i = 0; i < nbs.length; i++) if (!visited[nbs[i]]) count++;
      return count;
    }

    function dfs(cellIdx) {
      visited[cellIdx] = 1;
      path[depth++] = cellIdx;
      if (depth === size) return true;

      var nbs = neighbors(cellIdx).filter(function (nb) { return !visited[nb]; });
      shuffleInPlace(nbs, rand);
      // Warnsdorff's rule: try the most-constrained neighbor first. This is
      // what makes randomized backtracking actually finish fast on a grid
      // this size instead of thrashing through dead ends.
      nbs.sort(function (a, b) { return unvisitedDegree(a) - unvisitedDegree(b); });

      for (var i = 0; i < nbs.length; i++) {
        if (dfs(nbs[i])) return true;
      }

      visited[cellIdx] = 0;
      depth--;
      return false;
    }

    var size25 = size % 2 === 1;
    var starts = [];
    for (var i = 0; i < size; i++) {
      var r = Math.floor(i / n), c = i % n;
      if (!size25 || (r + c) % 2 === 0) starts.push(i);
    }
    shuffleInPlace(starts, rand);

    for (var s = 0; s < starts.length; s++) {
      visited = new Uint8Array(size);
      depth = 0;
      if (dfs(starts[s])) return Array.prototype.slice.call(path, 0, size);
    }
    return null; // exhausted every parity-valid start; shouldn't happen at 5x5/6x6
  }

  // ---- placing numbered stops along the finished line ----

  function placeCheckpoints(path, count, rand) {
    var L = path.length;
    var positions = [0];
    for (var i = 1; i < count - 1; i++) {
      var ideal = (i * (L - 1)) / (count - 1);
      var jitter = (rand() - 0.5) * ((L - 1) / (count - 1)) * 0.6;
      positions.push(Math.round(ideal + jitter));
    }
    positions.push(L - 1);
    positions.sort(function (a, b) { return a - b; });

    // Keep at least one un-numbered cell between consecutive stops so every
    // leg of the route is an actual routing decision, not a freebie.
    for (var p = 1; p < positions.length; p++) {
      if (positions[p] <= positions[p - 1] + 1) positions[p] = positions[p - 1] + 2;
    }
    var overflow = positions[positions.length - 1] - (L - 1);
    if (overflow > 0) {
      for (var q = positions.length - 1; q >= 0; q--) positions[q] -= overflow;
    }
    positions[0] = 0;
    positions[positions.length - 1] = L - 1;

    return positions.map(function (pos, i) {
      return { number: i + 1, cell: path[pos] };
    });
  }

  function checkpointCountFor(n, rand) {
    var base = n === 6 ? 8 : 6;
    var jitter = Math.floor(rand() * 3) - 1; // -1, 0, or +1
    return Math.max(5, base + jitter);
  }

  function sizeForDate(dateStr) {
    var day = new Date(dateStr + 'T00:00:00Z').getUTCDay(); // 0=Sun .. 6=Sat
    return (day === 3 || day === 6) ? 6 : 5; // Wed + Sat are the 6x6 challenge days
  }

  function generatePuzzle(seedStr, sizeOverride) {
    var rand = mulberry32(seedFromString(seedStr));
    var n = sizeOverride || sizeForDate(seedStr);
    var path = findHamiltonianPath(n, rand);
    if (!path) throw new Error('route-runner: no Hamiltonian path found for seed "' + seedStr + '"');
    var count = checkpointCountFor(n, rand);
    var checkpoints = placeCheckpoints(path, count, rand).map(function (cp) {
      return { number: cp.number, row: Math.floor(cp.cell / n), col: cp.cell % n };
    });
    var solution = path.map(function (cellIdx) {
      return [Math.floor(cellIdx / n), cellIdx % n];
    });
    return { seed: seedStr, size: n, checkpoints: checkpoints, solution: solution };
  }

  var api = {
    generatePuzzle: generatePuzzle,
    findHamiltonianPath: findHamiltonianPath,
    seedFromString: seedFromString,
    mulberry32: mulberry32,
    sizeForDate: sizeForDate
  };

  if (typeof module !== 'undefined' && module.exports) {
    module.exports = api;
  } else {
    root.RouteRunnerGen = api;
  }
})(typeof window !== 'undefined' ? window : globalThis);
